import numpy as np
import random as rnd

def generate_random_valid_jigsaw(n,m,seed):
    if seed is not None:
        rnd.seed(seed)


    #The puzzle should be generated by randomly assigning a color to each side of each piece, and then enforcing that the colorings are consistent at the edges of the pieces.
    #the colours should be integers from 0 to m-1.
    puzzle = np.zeros((n,n,4),dtype=int)
    #where the puzzle has size nxn and m is the number of "colorings" and 
    #seed is the seed for the random number generator.
    # The function should return a 3D numpy array of size nxnx4, where the first two dimensions represent the position of the piece in the grid and the third dimension represents the four sides of the piece.
    # and the sides are ordered [top, right, bottom, left].
    m = m - 1
    for y in range(0, n):
        for x in range(0, n):
            for i in range(0,4):
                puzzle[y][x][i] = rnd.randrange(1,m+1)

            if x != 0 and y != 0:
                puzzle[y][x][0] = puzzle[y-1][x][2]
                puzzle[y][x][3] = puzzle[y][x-1][1]
    

            if x == 0:
                puzzle[y][x][3] = 0
                if y != 0:
                    puzzle[y][x][0] = puzzle[y-1][x][2]

            elif x == n-1:
                puzzle[y][x][1] = 0
                if y == 0:
                    puzzle[y][x][0] = 0
                    puzzle[y][x][3] = puzzle[y][x-1][1]
                else:
                    puzzle[y][x][0] = puzzle[y-1][x][2]
                    puzzle[y][x][3] = puzzle[y][x-1][1]

            if y == 0:
                puzzle[y][x][0] = 0
                if x != 0:
                    puzzle[y][x][3] = puzzle[y][x-1][1]

            elif y == n-1:
                puzzle[y][x][2] = 0
                if x == 0:
                    puzzle[y][x][3] = 0
                    puzzle[y][x][0] = puzzle[y-1][x][2]
                else:
                    puzzle[y][x][3] = puzzle[y][x-1][1]
                    puzzle[y][x][0] = puzzle[y-1][x][2]
    #all puzzle entries should be integers:
    return puzzle

if __name__ == "__main__":
    generate_random_valid_jigsaw(3,3,1)
    print(generate_random_valid_jigsaw(3,3,1))